/**
 * Upload recipes to Firestore
 *
 * Usage:
 *   node scripts/uploadRecipes.js recipe.json
 *   node scripts/uploadRecipes.js recipe1.json recipe2.json recipe3.json
 *   node scripts/uploadRecipes.js recipes/*.json
 *
 * Requires scripts/serviceAccount.json (Firebase Console → Project Settings
 *   → Service accounts → Generate new private key)
 *
 * Each JSON file should follow the recipe schema. The document ID is
 * auto-generated by Firestore unless the JSON contains an "id" field,
 * in which case that is used as the document ID.
 */

const admin = require("firebase-admin");
const fs = require("fs");
const path = require("path");

// ── Init ─────────────────────────────────────────────────────────────────────
const serviceAccount = require("./serviceAccount.json");

admin.initializeApp({
	credential: admin.credential.cert(serviceAccount),
	projectId: "munchsprouts",
});

const db = admin.firestore();

// ── Helpers ───────────────────────────────────────────────────────────────────
function loadJson(filePath) {
	const abs = path.resolve(filePath);
	if (!fs.existsSync(abs)) {
		throw new Error(`File not found: ${abs}`);
	}
	const raw = fs.readFileSync(abs, "utf8");
	return JSON.parse(raw);
}

function validateRecipe(recipe, file) {
	const required = ["title", "category"];
	const missing = required.filter((k) => !recipe[k]);
	if (missing.length) {
		throw new Error(`${file}: missing required fields: ${missing.join(", ")}`);
	}
}

async function uploadRecipe(recipe, file) {
	validateRecipe(recipe, file);

	// Strip "id" from the data before saving — use it as doc ID if present
	const { id, ...data } = recipe;

	// Convert ISO date strings to Firestore Timestamps
	if (data.createdAt) {
		try {
			data.createdAt = admin.firestore.Timestamp.fromDate(new Date(data.createdAt));
		} catch {
			delete data.createdAt;
		}
	}

	let docRef;
	if (id) {
		docRef = db.collection("recipes").doc(id);
		await docRef.set(data, { merge: true });
		console.log(`  ✅ Uploaded to existing doc ID: ${id}`);
	} else {
		docRef = await db.collection("recipes").add(data);
		console.log(`  ✅ Created new doc ID: ${docRef.id}`);
	}

	return docRef.id;
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
	const files = process.argv.slice(2);

	if (files.length === 0) {
		console.error("Usage: node scripts/uploadRecipes.js <file.json> [file2.json ...]");
		process.exit(1);
	}

	console.log(`\n📤 Uploading ${files.length} recipe(s) to Firestore...\n`);

	let success = 0;
	let failed = 0;

	for (const file of files) {
		console.log(`📄 ${file}`);
		try {
			const recipe = loadJson(file);

			// Support both a single recipe object and an array of recipes
			const recipes = Array.isArray(recipe) ? recipe : [recipe];

			for (const r of recipes) {
				await uploadRecipe(r, file);
				success++;
			}
		} catch (e) {
			console.error(`  ❌ Failed: ${e.message}`);
			failed++;
		}
	}

	console.log(`\n──────────────────────────────`);
	console.log(`✅ Uploaded: ${success}`);
	if (failed > 0) console.log(`❌ Failed:   ${failed}`);
	console.log(`──────────────────────────────\n`);
}

main().catch(console.error).finally(() => process.exit());
