export const THEMES = {
	default: {
		bgMain: "#fbf7ef",
		bgPurple: "#f0ecfc",
		bgGreen: "#e8f5ee",
		bgWarning: "#fdf0e4",
		primaryPurple: "#9b7fe8",
		secondaryPurple: "#c4b0f0",
		primaryPurpleDark: "#7a5fcb",
		plum: "#6b4fa1",
		primaryGreen: "#4caf7d",
		primaryGreenLight: "#7dcf9e",
		primaryPinkDark: "#2e2440",
		textCharcoal: "#2e2440",
		warningStroke: "#e8995c",
		white: "#ffffff",
		border: "#e0d8f8",
		borderLight: "#ede8fb",
		mutedText: "#8a7aaa",
		statGreenBg: "#d4f0e0",
		statGreenText: "#2d7a55",
		statRedBg: "#fad4d4",
		statRedText: "#a83232",
		statBlueBg: "#d4e8f5",
		statBlueText: "#2a5f8f",
		statOrangeBg: "#fde8cc",
		statOrangeText: "#a85a1a",
		statNeutralBg: "#fde8cc",
		statNeutralText: "#7a5a1a",
		card: "#ffffff",
		screen: "#f0ecfc",
		navBg: "#ffffff",
	},
	dark: {
		bgMain: "#121212",
		bgPurple: "#f0ecfc",
		bgGreen: "#0d2b1e",
		bgWarning: "#2b1e0d",
		primaryPurple: "#b39dfa",
		secondaryPurple: "#7c6bbf",
		primaryPurpleDark: "#d4c4ff",
		primaryGreen: "#4dd494",
		primaryGreenLight: "#2ea868",
		primaryPinkDark: "#b27bf5",
		textCharcoal: "#f0ecff",
		warningStroke: "#f0a060",
		white: "#1e1e2e",
		border: "#3a3060",
		borderLight: "#2e2448",
		mutedText: "#9988cc",
		statGreenBg: "#d4f0e0",
		statGreenText: "#4dd494",
		statRedBg: "#fad4d4",
		statRedText: "#f07070",
		statBlueBg: "#d4e8f5",
		statBlueText: "#70b8f0",
		statOrangeBg: "#2b1a0d",
		statOrangeText: "#f0a060",
		statNeutralBg: "#fde8cc",
		statNeutralText: "#d4a060",
		card: "#1e1e2e",
		screen: "#121212",
		navBg: "#1a1a2e",
	},
	accessible: {
		bgMain: "#ffffff",
		bgPurple: "#e8e0ff",
		bgGreen: "#d0f0e0",
		bgWarning: "#fff0d0",
		primaryPurple: "#5000cc",
		secondaryPurple: "#7730dd",
		primaryPurpleDark: "#3800aa",
		primaryGreen: "#007740",
		primaryGreenLight: "#009950",
		primaryPinkDark: "#000000",
		textCharcoal: "#000000",
		warningStroke: "#c84800",
		white: "#ffffff",
		border: "#000000",
		borderLight: "#333333",
		mutedText: "#444444",
		statGreenBg: "#d0f0e0",
		statGreenText: "#004d28",
		statRedBg: "#ffe0e0",
		statRedText: "#8b0000",
		statBlueBg: "#d0e8ff",
		statBlueText: "#003380",
		statOrangeBg: "#fff0d0",
		statOrangeText: "#7a3000",
		statNeutralBg: "#f0f0d0",
		statNeutralText: "#4a4000",
		card: "#ffffff",
		screen: "#f8f8f8",
		navBg: "#ffffff",
	},
};

export const CATEGORIES = [
	{ value: "Vegetables", color: "#4caf7d", bg: "#d4f0e0" },
	{ value: "Fruits", color: "#e05c7a", bg: "#fad4de" },
	{ value: "Grains", color: "#d4a017", bg: "#fde8cc" },
	{ value: "Proteins", color: "#e07b39", bg: "#fde8d4" },
	{ value: "Dairy", color: "#9b7fe8", bg: "#ede8f7" },
	{ value: "Legumes", color: "#3db8a0", bg: "#d4f0ea" },
	{ value: "Liquids", color: "#4ab8d8", bg: "#d4eef5" },
	{ value: "Other", color: "#8a7aaa", bg: "#ece8f9" },
];

export const FORMS = [
	"Purée",
	"Mashed",
	"Soft/Cut",
	"Finger Food",
	"Mixed Texture",
	"Liquid",
	"Sippy Cup",
	"Open Cup",
];

export const REACTIONS = [
	{ value: "Loved", color: "#2d7a55", bg: "#d4f0e0", border: "#a8dcc0" },
	{ value: "Good", color: "#3a7a3a", bg: "#ddf0dd", border: "#a8d8a8" },
	{ value: "Neutral", color: "#7a5a1a", bg: "#fde8cc", border: "#ddc8a8" },
	{ value: "Rejected", color: "#a83232", bg: "#fad4d4", border: "#dca8a8" },
	{ value: "Allergic", color: "#c0392b", bg: "#fde8e8", border: "#e07070" },
];

export const MEAL_TIMES = [
	{ value: "Breakfast", color: "#d4860a", bg: "#fff0cc" },
	{ value: "Morning Snack", color: "#a85a1a", bg: "#fde8d4" },
	{ value: "Lunch", color: "#2d7a55", bg: "#d4f0e0" },
	{ value: "Afternoon Snack", color: "#3a7a3a", bg: "#ddf0dd" },
	{ value: "Dinner / Tea", color: "#2a5f8f", bg: "#d4e8f5" },
	{ value: "Drink", color: "#4ab8d8", bg: "#d4eef5" },
];

export const MONTHS = [
	"Jan",
	"Feb",
	"Mar",
	"Apr",
	"May",
	"Jun",
	"Jul",
	"Aug",
	"Sep",
	"Oct",
	"Nov",
	"Dec",
];

export const ALLERGENS = [
	{ value: "Gluten", emoji: "🌾", color: "#d4860a", bg: "#fff0cc" },
	{ value: "Dairy", emoji: "🥛", color: "#9b7fe8", bg: "#ede8f7" },
	{ value: "Eggs", emoji: "🥚", color: "#e05c7a", bg: "#fad4de" },
	{ value: "Peanuts", emoji: "🥜", color: "#a85a1a", bg: "#fde8d4" },
	{ value: "Tree Nuts", emoji: "🌰", color: "#7a5a1a", bg: "#f5e8d0" },
	{ value: "Fish", emoji: "🐟", color: "#2a5f8f", bg: "#d4e8f5" },
	{ value: "Shellfish", emoji: "🦐", color: "#c0392b", bg: "#fde8e8" },
	{ value: "Soy", emoji: "🫘", color: "#3db87a", bg: "#d4f0e0" },
	{ value: "Sesame", emoji: "🌿", color: "#8a7aaa", bg: "#ece8f9" },
];
