import { createContext, useContext, useMemo } from "react";
import { StyleSheet } from "react-native";
import { THEMES } from "./constants";

// Font family constants — populated once fonts are loaded via useFonts in App.js
export const FONTS = {
	displayBold:    "PlusJakartaSans_700Bold",
	displaySemi:    "PlusJakartaSans_600SemiBold",
	displayMedium:  "PlusJakartaSans_500Medium",
	display:        "PlusJakartaSans_400Regular",
	bodyExtraBold:  "NunitoSans_800ExtraBold",
	bodyBold:       "NunitoSans_700Bold",
	bodySemi:       "NunitoSans_600SemiBold",
	body:           "NunitoSans_400Regular",
};

export const ThemeContext = createContext({
	theme: "default",
	C: THEMES.default,
	setTheme: () => {},
});

export const useTheme = () => useContext(ThemeContext);

// useStyles replaces the old module-level StyleSheet.create(s).
// By reading C from context inside a hook, styles always reflect the active theme.
export function useStyles() {
	const { C } = useTheme();
	return useMemo(
		() =>
			StyleSheet.create({
				card: {
					backgroundColor: C.white,
					borderRadius: 20,
					padding: 18,
					borderWidth: 1.5,
					borderColor: C.primaryPurple + "50",
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.08,
					shadowRadius: 12,
					shadowOffset: { width: 0, height: 4 },
					elevation: 3,
				},
				header: {
					backgroundColor: C.screen,
					paddingHorizontal: 20,
					paddingVertical: 12,
					flexDirection: "row",
					alignItems: "center",
					justifyContent: "space-between",
				},
				appName: {
					fontFamily: "PlusJakartaSans_700Bold",
					fontSize: 20,
					color: C.primaryPinkDark,
					letterSpacing: 0.2,
				},
				pageSubtitle: {
					fontFamily: "NunitoSans_400Regular",
					fontSize: 12,
					color: C.mutedText,
					marginTop: 1,
				},
				pageTitle: {
					fontFamily: "PlusJakartaSans_700Bold",
					fontSize: 24,
					color: C.primaryPinkDark,
				},
				sectionTitle: {
					fontFamily: "PlusJakartaSans_600SemiBold",
					fontSize: 17,
					color: C.primaryPinkDark,
				},
				smallLabel: {
					fontFamily: "NunitoSans_700Bold",
					fontSize: 11,
					color: C.mutedText,
					textTransform: "uppercase",
					letterSpacing: 0.6,
				},
				label: {
					fontFamily: "NunitoSans_700Bold",
					fontSize: 12,
					color: C.mutedText,
					textTransform: "uppercase",
					letterSpacing: 0.5,
					marginBottom: 6,
				},
				input: {
					borderWidth: 1.5,
					borderColor: C.primaryPurple + "70",
					borderRadius: 16,
					paddingHorizontal: 16,
					paddingVertical: 13,
					backgroundColor: C.white,
					color: C.textCharcoal,
					fontFamily: "NunitoSans_600SemiBold",
					fontSize: 15,
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.06,
					shadowRadius: 4,
					shadowOffset: { width: 0, height: 2 },
					elevation: 1,
				},
				btnPrimary: {
					backgroundColor: C.primaryPurple,
					borderRadius: 18,
					paddingVertical: 15,
					paddingHorizontal: 20,
					alignItems: "center",
					justifyContent: "center",
					width: "100%",
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.35,
					shadowRadius: 10,
					shadowOffset: { width: 0, height: 5 },
					elevation: 5,
				},
				btnPrimaryText: {
					color: C.white,
					fontFamily: "NunitoSans_700Bold",
					fontSize: 15,
					letterSpacing: 0.3,
				},
				btnOutline: {
					backgroundColor: "transparent",
					borderWidth: 1.5,
					borderColor: C.primaryPurple,
					borderRadius: 16,
					paddingVertical: 11,
					paddingHorizontal: 18,
					alignItems: "center",
					justifyContent: "center",
				},
				btnOutlineText: {
					color: C.primaryPurple,
					fontFamily: "NunitoSans_700Bold",
					fontSize: 13,
				},
				btnSecondary: {
					backgroundColor: C.bgPurple,
					borderRadius: 12,
					padding: 9,
					borderWidth: 1,
					borderColor: C.primaryPurple + "40",
				},
				btnDanger: { backgroundColor: C.statRedBg, borderRadius: 12, padding: 9, borderWidth: 1, borderColor: "#f5c6c6" },
				statCard: {
					borderRadius: 16,
					padding: 14,
					gap: 4,
					alignItems: "center",
					borderWidth: 1,
					borderColor: C.primaryPurple + "40",
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.07,
					shadowRadius: 8,
					shadowOffset: { width: 0, height: 3 },
					elevation: 2,
				},
				statValue: {
					fontFamily: "PlusJakartaSans_700Bold",
					fontSize: 24,
					lineHeight: 26,
				},
				statLabel: {
					fontFamily: "NunitoSans_700Bold",
					fontSize: 10,
					lineHeight: 12,
				},
				bottomNav: {
					backgroundColor: C.white,
					flexDirection: "row",
					paddingTop: 8,
					paddingHorizontal: 6,
					borderTopLeftRadius: 24,
					borderTopRightRadius: 24,
					borderTopWidth: 1.5,
					borderLeftWidth: 1.5,
					borderRightWidth: 1.5,
					borderColor: C.primaryPurple + "60",
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.15,
					shadowRadius: 20,
					shadowOffset: { width: 0, height: -6 },
					elevation: 12,
				},
				navItem: {
					flex: 1,
					alignItems: "center",
					paddingBottom: 4,
					paddingTop: 2,
				},
				navLabel: {
					fontFamily: "NunitoSans_600SemiBold",
					fontSize: 10,
					color: C.mutedText,
				},
				navDot: {
					width: 4,
					height: 4,
					backgroundColor: C.primaryPurple,
					borderRadius: 2,
					marginTop: 1,
				},
				navAddBtn: {
					backgroundColor: C.primaryPurple,
					borderRadius: 18,
					width: 52,
					height: 52,
					alignItems: "center",
					justifyContent: "center",
					marginTop: -18,
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.55,
					shadowRadius: 12,
					shadowOffset: { width: 0, height: 5 },
					elevation: 10,
				},
				modalOverlay: {
					flex: 1,
					backgroundColor: "rgba(46,36,64,0.4)",
					justifyContent: "flex-end",
				},
				modalSheet: {
					backgroundColor: C.white,
					borderTopLeftRadius: 32,
					borderTopRightRadius: 32,
					padding: 28,
					maxHeight: "92%",
					borderTopWidth: 1.5,
					borderLeftWidth: 1.5,
					borderRightWidth: 1.5,
					borderColor: C.primaryPurple + "40",
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.16,
					shadowRadius: 28,
					elevation: 20,
				},
				modalTitle: {
					fontFamily: "PlusJakartaSans_700Bold",
					fontSize: 22,
					color: C.primaryPinkDark,
				},
				pickerOverlay: {
					flex: 1,
					backgroundColor: "rgba(46,36,64,0.4)",
					justifyContent: "flex-end",
				},
				pickerSheet: {
					backgroundColor: C.white,
					borderTopLeftRadius: 32,
					borderTopRightRadius: 32,
					padding: 24,
					maxHeight: "65%",
					borderTopWidth: 1.5,
					borderLeftWidth: 1.5,
					borderRightWidth: 1.5,
					borderColor: C.primaryPurple + "40",
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.16,
					shadowRadius: 28,
					elevation: 20,
				},
				pickerTitle: {
					fontFamily: "PlusJakartaSans_600SemiBold",
					fontSize: 18,
					color: C.primaryPinkDark,
					marginBottom: 16,
				},
				pickerItem: {
					flexDirection: "row",
					justifyContent: "space-between",
					alignItems: "center",
					paddingVertical: 14,
					paddingHorizontal: 12,
					borderRadius: 14,
					marginBottom: 4,
				},
				pickerItemText: {
					fontFamily: "NunitoSans_600SemiBold",
					fontSize: 15,
					color: C.textCharcoal,
				},
				tagPurple: {
					backgroundColor: C.bgPurple,
					borderRadius: 999,
					paddingHorizontal: 10,
					paddingVertical: 4,
				},
				tagPurpleText: {
					fontFamily: "NunitoSans_700Bold",
					fontSize: 11,
					color: C.primaryPurple,
				},
				tagGreen: {
					backgroundColor: C.bgGreen,
					borderRadius: 999,
					paddingHorizontal: 10,
					paddingVertical: 4,
				},
				tagGreenText: {
					fontFamily: "NunitoSans_700Bold",
					fontSize: 11,
					color: C.primaryGreen,
				},
				tagWarning: {
					backgroundColor: C.bgWarning,
					borderRadius: 999,
					paddingHorizontal: 10,
					paddingVertical: 4,
				},
				tagWarningText: {
					fontFamily: "NunitoSans_700Bold",
					fontSize: 11,
					color: C.warningStroke,
				},
				toastContainer: {
					position: "absolute",
					bottom: 100,
					right: 16,
					gap: 8,
					zIndex: 9999,
				},
				toast: {
					borderRadius: 14,
					paddingHorizontal: 16,
					paddingVertical: 12,
					maxWidth: 280,
					shadowColor: "#2e2440",
					shadowOpacity: 0.14,
					shadowRadius: 12,
					elevation: 8,
				},
			}),
		[C],
	);
}
