import { createContext, useContext, useMemo } from "react";
import { StyleSheet } from "react-native";
import { THEMES } from "./constants";

export const ThemeContext = createContext({
	theme: "default",
	C: THEMES.default,
	setTheme: () => {},
});

export const useTheme = () => useContext(ThemeContext);

// useStyles replaces the old module-level StyleSheet.create(s).
// By reading C from context inside a hook, styles always reflect the active theme.
export function useStyles() {
	const { C } = useTheme();
	return useMemo(
		() =>
			StyleSheet.create({
				card: {
					backgroundColor: C.white,
					borderRadius: 20,
					padding: 18,
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.15,
					shadowRadius: 18,
					shadowOffset: { width: 0, height: 6 },
					elevation: 6,
				},
				header: {
					backgroundColor: C.white,
					paddingHorizontal: 20,
					paddingVertical: 14,
					flexDirection: "row",
					alignItems: "center",
					justifyContent: "space-between",
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.14,
					shadowRadius: 14,
					shadowOffset: { width: 0, height: 4 },
					elevation: 5,
				},
				appName: {
					fontWeight: "800",
					fontSize: 19,
					color: C.primaryPinkDark,
					letterSpacing: 0.2,
				},
				pageSubtitle: { fontSize: 12, color: C.mutedText, marginTop: 1 },
				pageTitle: { fontWeight: "800", fontSize: 22, color: C.primaryPinkDark },
				sectionTitle: { fontWeight: "700", fontSize: 16, color: C.primaryPinkDark },
				smallLabel: {
					fontSize: 11,
					fontWeight: "700",
					color: C.mutedText,
					textTransform: "uppercase",
					letterSpacing: 0.6,
				},
				label: {
					fontSize: 12,
					fontWeight: "700",
					color: C.mutedText,
					textTransform: "uppercase",
					letterSpacing: 0.5,
					marginBottom: 6,
				},
				input: {
					borderWidth: 1.5,
					borderColor: C.borderLight,
					borderRadius: 14,
					paddingHorizontal: 16,
					paddingVertical: 12,
					backgroundColor: C.white,
					color: C.textCharcoal,
					fontWeight: "600",
					fontSize: 15,
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.08,
					shadowRadius: 6,
					shadowOffset: { width: 0, height: 2 },
					elevation: 2,
				},
				btnPrimary: {
					backgroundColor: C.primaryPurple,
					borderRadius: 16,
					paddingVertical: 15,
					paddingHorizontal: 20,
					alignItems: "center",
					justifyContent: "center",
					width: "100%",
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.4,
					shadowRadius: 12,
					shadowOffset: { width: 0, height: 6 },
					elevation: 6,
				},
				btnPrimaryText: {
					color: C.white,
					fontWeight: "700",
					fontSize: 15,
					letterSpacing: 0.3,
				},
				btnOutline: {
					backgroundColor: "transparent",
					borderWidth: 2,
					borderColor: C.primaryPurple,
					borderRadius: 14,
					paddingVertical: 11,
					paddingHorizontal: 18,
					alignItems: "center",
					justifyContent: "center",
				},
				btnOutlineText: { color: C.primaryPurple, fontWeight: "700", fontSize: 13 },
				btnSecondary: {
					backgroundColor: C.bgPurple,
					borderRadius: 12,
					padding: 9,
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.1,
					shadowRadius: 4,
					elevation: 1,
				},
				btnDanger: { backgroundColor: C.statRedBg, borderRadius: 12, padding: 9 },
				statCard: {
					borderRadius: 16,
					padding: 12,
					gap: 4,
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.1,
					shadowRadius: 10,
					shadowOffset: { width: 0, height: 4 },
					elevation: 3,
				},
				statValue: { fontSize: 22, fontWeight: "800", lineHeight: 24 },
				statLabel: { fontSize: 10, fontWeight: "700", lineHeight: 12 },
				bottomNav: {
					backgroundColor: C.white,
					flexDirection: "row",
					paddingTop: 8,
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.15,
					shadowRadius: 20,
					shadowOffset: { width: 0, height: -6 },
					elevation: 14,
				},
				navItem: {
					flex: 1,
					alignItems: "center",
					gap: 3,
					paddingBottom: 4,
					paddingTop: 2,
				},
				navLabel: { fontSize: 10, fontWeight: "600", color: C.mutedText },
				navDot: {
					width: 4,
					height: 4,
					backgroundColor: C.primaryPurple,
					borderRadius: 2,
					marginTop: 1,
				},
				navAddBtn: {
					backgroundColor: C.primaryPurple,
					borderRadius: 18,
					width: 52,
					height: 52,
					alignItems: "center",
					justifyContent: "center",
					marginTop: -18,
					shadowColor: C.primaryPurple,
					shadowOpacity: 0.55,
					shadowRadius: 12,
					shadowOffset: { width: 0, height: 5 },
					elevation: 10,
				},
				modalOverlay: {
					flex: 1,
					backgroundColor: "rgba(90,45,122,0.35)",
					justifyContent: "flex-end",
				},
				modalSheet: {
					backgroundColor: C.white,
					borderTopLeftRadius: 28,
					borderTopRightRadius: 28,
					padding: 28,
					maxHeight: "92%",
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.2,
					shadowRadius: 24,
					elevation: 20,
				},
				modalTitle: { fontWeight: "800", fontSize: 20, color: C.primaryPinkDark },
				pickerOverlay: {
					flex: 1,
					backgroundColor: "rgba(90,45,122,0.35)",
					justifyContent: "flex-end",
				},
				pickerSheet: {
					backgroundColor: C.white,
					borderTopLeftRadius: 28,
					borderTopRightRadius: 28,
					padding: 24,
					maxHeight: "65%",
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.2,
					shadowRadius: 24,
					elevation: 20,
				},
				pickerTitle: {
					fontWeight: "700",
					fontSize: 16,
					color: C.primaryPinkDark,
					marginBottom: 16,
				},
				pickerItem: {
					flexDirection: "row",
					justifyContent: "space-between",
					alignItems: "center",
					paddingVertical: 14,
					paddingHorizontal: 12,
					borderRadius: 14,
					marginBottom: 4,
				},
				pickerItemText: { fontSize: 15, color: C.textCharcoal, fontWeight: "600" },
				tagPurple: {
					backgroundColor: C.bgPurple,
					borderRadius: 999,
					paddingHorizontal: 10,
					paddingVertical: 4,
				},
				tagPurpleText: { fontSize: 11, fontWeight: "700", color: C.primaryPurple },
				tagGreen: {
					backgroundColor: C.bgGreen,
					borderRadius: 999,
					paddingHorizontal: 10,
					paddingVertical: 4,
				},
				tagGreenText: { fontSize: 11, fontWeight: "700", color: C.primaryGreen },
				tagWarning: {
					backgroundColor: C.bgWarning,
					borderRadius: 999,
					paddingHorizontal: 10,
					paddingVertical: 4,
				},
				tagWarningText: { fontSize: 11, fontWeight: "700", color: C.warningStroke },
				toastContainer: {
					position: "absolute",
					bottom: 100,
					right: 16,
					gap: 8,
					zIndex: 9999,
				},
				toast: {
					borderRadius: 14,
					paddingHorizontal: 16,
					paddingVertical: 12,
					maxWidth: 280,
					shadowColor: "#9b7fe8",
					shadowOpacity: 0.18,
					shadowRadius: 12,
					elevation: 8,
				},
			}),
		[C],
	);
}
